apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: postgres-app-pod
    app: voting-app
