apiVersion: v1
kind: Pod
metadata:
  name: posgtgres-app-pod
  labels:
    name: postgres-app-pod
    app: voting-app

spec:
  containers:
  - name: postgres-app-pod
    image: postgres:9.4
    ports:
    - containerPort: 5432
